export interface InventorySeedData {
  facilityId: string;
  drugId: string;
  currentStock: number;
  avgDailyConsumption: number;
  safetyStock: number;
  daysCover: number;
  daysCoverPipeline: number;
  pipelineUnits: number;
  nextDeliveryDays: number | null;
  replenishmentStatus: "On Track" | "Delayed" | "Critical Delay" | "In Transit";
  riskProbability: number;
  riskStatus: "critical" | "warning" | "low";
  riskDriver: string;
}

export const ALL_INVENTORY_SEEDS: InventorySeedData[] = [
  // =========================================================================
  // 1. CEFTRIAXONE 1G INJ (CRITICAL ANTIBIOTIC)
  // =========================================================================
  {
    facilityId: "fac-pune-dh",
    drugId: "drug-ceftriaxone",
    currentStock: 384,
    avgDailyConsumption: 80,
    safetyStock: 800,
    daysCover: 4.8,
    daysCoverPipeline: 7.3,
    pipelineUnits: 200,
    nextDeliveryDays: 9,
    replenishmentStatus: "Delayed",
    riskProbability: 0.88,
    riskStatus: "critical",
    riskDriver: "Replenishment delay (6d overdue) + 38% patient surge",
  },
  {
    facilityId: "fac-pune-sdh-1",
    drugId: "drug-ceftriaxone",
    currentStock: 1000,
    avgDailyConsumption: 35,
    safetyStock: 350,
    daysCover: 28.6,
    daysCoverPipeline: 40.0,
    pipelineUnits: 400,
    nextDeliveryDays: 6,
    replenishmentStatus: "On Track",
    riskProbability: 0.08,
    riskStatus: "low",
    riskDriver: "Ample tertiary stock reserve with scheduled bulk delivery",
  },
  {
    facilityId: "fac-pune-sdh-2",
    drugId: "drug-ceftriaxone",
    currentStock: 320,
    avgDailyConsumption: 28,
    safetyStock: 280,
    daysCover: 11.4,
    daysCoverPipeline: 16.8,
    pipelineUnits: 150,
    nextDeliveryDays: 7,
    replenishmentStatus: "On Track",
    riskProbability: 0.42,
    riskStatus: "warning",
    riskDriver: "Elevated ICU antibiotic consumption; buffer dipping below 14d",
  },
  {
    facilityId: "fac-pune-chc-1",
    drugId: "drug-ceftriaxone",
    currentStock: 90,
    avgDailyConsumption: 22,
    safetyStock: 220,
    daysCover: 4.1,
    daysCoverPipeline: 7.7,
    pipelineUnits: 80,
    nextDeliveryDays: 8,
    replenishmentStatus: "Delayed",
    riskProbability: 0.82,
    riskStatus: "critical",
    riskDriver: "Critical spillover deflection load from Aundh DH",
  },
  {
    facilityId: "fac-pune-chc-2",
    drugId: "drug-ceftriaxone",
    currentStock: 60,
    avgDailyConsumption: 16,
    safetyStock: 160,
    daysCover: 3.8,
    daysCoverPipeline: 5.6,
    pipelineUnits: 30,
    nextDeliveryDays: 10,
    replenishmentStatus: "Delayed",
    riskProbability: 0.86,
    riskStatus: "critical",
    riskDriver: "Late distributor dispatch + remote highland transport delay",
  },
  {
    facilityId: "fac-pune-chc-3",
    drugId: "drug-ceftriaxone",
    currentStock: 370,
    avgDailyConsumption: 14,
    safetyStock: 140,
    daysCover: 26.4,
    daysCoverPipeline: 40.7,
    pipelineUnits: 200,
    nextDeliveryDays: 5,
    replenishmentStatus: "On Track",
    riskProbability: 0.10,
    riskStatus: "low",
    riskDriver: "Robust regional buffer under regular fortnightly reorder",
  },
  {
    facilityId: "fac-pune-phc-1",
    drugId: "drug-ceftriaxone",
    currentStock: 45,
    avgDailyConsumption: 5,
    safetyStock: 50,
    daysCover: 9.0,
    daysCoverPipeline: 14.0,
    pipelineUnits: 25,
    nextDeliveryDays: 6,
    replenishmentStatus: "On Track",
    riskProbability: 0.45,
    riskStatus: "warning",
    riskDriver: "Moderate rural buffer; awaiting secondary batch dispatch",
  },
  {
    facilityId: "fac-pune-phc-2",
    drugId: "drug-ceftriaxone",
    currentStock: 150,
    avgDailyConsumption: 6,
    safetyStock: 60,
    daysCover: 25.0,
    daysCoverPipeline: 33.3,
    pipelineUnits: 50,
    nextDeliveryDays: 7,
    replenishmentStatus: "On Track",
    riskProbability: 0.09,
    riskStatus: "low",
    riskDriver: "Well-stocked dispensary with stable baseline demand",
  },
  {
    facilityId: "fac-pune-phc-3",
    drugId: "drug-ceftriaxone",
    currentStock: 90,
    avgDailyConsumption: 4.2,
    safetyStock: 40,
    daysCover: 21.4,
    daysCoverPipeline: 31.0,
    pipelineUnits: 40,
    nextDeliveryDays: 8,
    replenishmentStatus: "On Track",
    riskProbability: 0.12,
    riskStatus: "low",
    riskDriver: "Dispensary reserves stable; telemetry live and synced",
  },
  {
    facilityId: "fac-thane-dh",
    drugId: "drug-ceftriaxone",
    currentStock: 290,
    avgDailyConsumption: 70,
    safetyStock: 700,
    daysCover: 4.1,
    daysCoverPipeline: 6.3,
    pipelineUnits: 150,
    nextDeliveryDays: 10,
    replenishmentStatus: "Critical Delay",
    riskProbability: 0.92,
    riskStatus: "critical",
    riskDriver: "Port logistics bottleneck + vendor manufacturing halt",
  },
  {
    facilityId: "fac-thane-sdh-1",
    drugId: "drug-ceftriaxone",
    currentStock: 280,
    avgDailyConsumption: 28,
    safetyStock: 280,
    daysCover: 10.0,
    daysCoverPipeline: 14.3,
    pipelineUnits: 120,
    nextDeliveryDays: 5,
    replenishmentStatus: "Delayed",
    riskProbability: 0.48,
    riskStatus: "warning",
    riskDriver: "Secondary spillover incoming from Thane Civil trauma ward",
  },
  {
    facilityId: "fac-thane-chc-1",
    drugId: "drug-ceftriaxone",
    currentStock: 450,
    avgDailyConsumption: 18,
    safetyStock: 180,
    daysCover: 25.0,
    daysCoverPipeline: 35.0,
    pipelineUnits: 180,
    nextDeliveryDays: 6,
    replenishmentStatus: "On Track",
    riskProbability: 0.11,
    riskStatus: "low",
    riskDriver: "Adequate municipal reserve maintained by urban health mission",
  },
  {
    facilityId: "fac-thane-phc-1",
    drugId: "drug-ceftriaxone",
    currentStock: 90,
    avgDailyConsumption: 4,
    safetyStock: 40,
    daysCover: 22.5,
    daysCoverPipeline: 30.0,
    pipelineUnits: 30,
    nextDeliveryDays: 7,
    replenishmentStatus: "On Track",
    riskProbability: 0.14,
    riskStatus: "low",
    riskDriver: "Protected rural dispensary allocation on track",
  },

  // =========================================================================
  // 2. OXYTOCIN 10 IU/ML (MATERNAL HEALTH)
  // =========================================================================
  {
    facilityId: "fac-pune-dh",
    drugId: "drug-oxytocin",
    currentStock: 1700,
    avgDailyConsumption: 65,
    safetyStock: 650,
    daysCover: 26.2,
    daysCoverPipeline: 36.9,
    pipelineUnits: 700,
    nextDeliveryDays: 6,
    replenishmentStatus: "On Track",
    riskProbability: 0.08,
    riskStatus: "low",
    riskDriver: "State-of-the-art cold chain repository with deep maternal inventory",
  },
  {
    facilityId: "fac-pune-sdh-1",
    drugId: "drug-oxytocin",
    currentStock: 240,
    avgDailyConsumption: 25,
    safetyStock: 250,
    daysCover: 9.6,
    daysCoverPipeline: 15.6,
    pipelineUnits: 150,
    nextDeliveryDays: 4,
    replenishmentStatus: "On Track",
    riskProbability: 0.44,
    riskStatus: "warning",
    riskDriver: "Maternity ward admissions surge +24% during monsoon births",
  },
  {
    facilityId: "fac-pune-sdh-2",
    drugId: "drug-oxytocin",
    currentStock: 560,
    avgDailyConsumption: 20,
    safetyStock: 200,
    daysCover: 28.0,
    daysCoverPipeline: 40.5,
    pipelineUnits: 250,
    nextDeliveryDays: 7,
    replenishmentStatus: "On Track",
    riskProbability: 0.09,
    riskStatus: "low",
    riskDriver: "Consistent cold chain storage and steady labor delivery rates",
  },
  {
    facilityId: "fac-pune-chc-1",
    drugId: "drug-oxytocin",
    currentStock: 330,
    avgDailyConsumption: 15,
    safetyStock: 150,
    daysCover: 22.0,
    daysCoverPipeline: 30.0,
    pipelineUnits: 120,
    nextDeliveryDays: 5,
    replenishmentStatus: "On Track",
    riskProbability: 0.12,
    riskStatus: "low",
    riskDriver: "Protected maternal emergency stash safely above threshold",
  },
  {
    facilityId: "fac-pune-chc-2",
    drugId: "drug-oxytocin",
    currentStock: 120,
    avgDailyConsumption: 12,
    safetyStock: 120,
    daysCover: 10.0,
    daysCoverPipeline: 15.0,
    pipelineUnits: 60,
    nextDeliveryDays: 6,
    replenishmentStatus: "Delayed",
    riskProbability: 0.49,
    riskStatus: "warning",
    riskDriver: "Cold chain temperature fluctuations flagged; reorder pending",
  },
  {
    facilityId: "fac-pune-chc-3",
    drugId: "drug-oxytocin",
    currentStock: 42,
    avgDailyConsumption: 10,
    safetyStock: 100,
    daysCover: 4.2,
    daysCoverPipeline: 7.2,
    pipelineUnits: 30,
    nextDeliveryDays: 8,
    replenishmentStatus: "Delayed",
    riskProbability: 0.85,
    riskStatus: "critical",
    riskDriver: "Cold chain unit compressor failure + delayed replacement stock",
  },
  {
    facilityId: "fac-pune-phc-1",
    drugId: "drug-oxytocin",
    currentStock: 10,
    avgDailyConsumption: 3,
    safetyStock: 30,
    daysCover: 3.3,
    daysCoverPipeline: 8.3,
    pipelineUnits: 15,
    nextDeliveryDays: 9,
    replenishmentStatus: "Delayed",
    riskProbability: 0.89,
    riskStatus: "critical",
    riskDriver: "Critical depletion after multiple emergency night deliveries",
  },
  {
    facilityId: "fac-pune-phc-2",
    drugId: "drug-oxytocin",
    currentStock: 100,
    avgDailyConsumption: 4,
    safetyStock: 40,
    daysCover: 25.0,
    daysCoverPipeline: 35.0,
    pipelineUnits: 40,
    nextDeliveryDays: 6,
    replenishmentStatus: "On Track",
    riskProbability: 0.10,
    riskStatus: "low",
    riskDriver: "Routine maternal care buffer under weekly inspection",
  },
  {
    facilityId: "fac-pune-phc-3",
    drugId: "drug-oxytocin",
    currentStock: 26,
    avgDailyConsumption: 3,
    safetyStock: 30,
    daysCover: 8.7,
    daysCoverPipeline: 15.3,
    pipelineUnits: 20,
    nextDeliveryDays: 5,
    replenishmentStatus: "On Track",
    riskProbability: 0.46,
    riskStatus: "warning",
    riskDriver: "Low maternal reserve; scheduled delivery expected in 5 days",
  },
  {
    facilityId: "fac-thane-dh",
    drugId: "drug-oxytocin",
    currentStock: 2100,
    avgDailyConsumption: 70,
    safetyStock: 700,
    daysCover: 30.0,
    daysCoverPipeline: 41.4,
    pipelineUnits: 800,
    nextDeliveryDays: 6,
    replenishmentStatus: "On Track",
    riskProbability: 0.07,
    riskStatus: "low",
    riskDriver: "Regional tertiary hub with surplus cold-chain reserve",
  },
  {
    facilityId: "fac-thane-sdh-1",
    drugId: "drug-oxytocin",
    currentStock: 120,
    avgDailyConsumption: 28,
    safetyStock: 280,
    daysCover: 4.3,
    daysCoverPipeline: 7.1,
    pipelineUnits: 80,
    nextDeliveryDays: 8,
    replenishmentStatus: "Delayed",
    riskProbability: 0.86,
    riskStatus: "critical",
    riskDriver: "High maternal referral inflow + vendor delivery backlog",
  },
  {
    facilityId: "fac-thane-chc-1",
    drugId: "drug-oxytocin",
    currentStock: 160,
    avgDailyConsumption: 16,
    safetyStock: 160,
    daysCover: 10.0,
    daysCoverPipeline: 14.4,
    pipelineUnits: 70,
    nextDeliveryDays: 5,
    replenishmentStatus: "On Track",
    riskProbability: 0.44,
    riskStatus: "warning",
    riskDriver: "Elevated obstetric demand; buffer approaching caution line",
  },
  {
    facilityId: "fac-thane-phc-1",
    drugId: "drug-oxytocin",
    currentStock: 70,
    avgDailyConsumption: 3,
    safetyStock: 30,
    daysCover: 23.3,
    daysCoverPipeline: 31.7,
    pipelineUnits: 25,
    nextDeliveryDays: 6,
    replenishmentStatus: "On Track",
    riskProbability: 0.12,
    riskStatus: "low",
    riskDriver: "Stable rural maternal health kit deployment",
  },

  // =========================================================================
  // 3. ARTESUNATE 60MG INJ (ANTIMALARIAL CARE)
  // =========================================================================
  {
    facilityId: "fac-pune-dh",
    drugId: "drug-artesunate",
    currentStock: 440,
    avgDailyConsumption: 40,
    safetyStock: 400,
    daysCover: 11.0,
    daysCoverPipeline: 16.0,
    pipelineUnits: 200,
    nextDeliveryDays: 5,
    replenishmentStatus: "On Track",
    riskProbability: 0.45,
    riskStatus: "warning",
    riskDriver: "Monsoon vector admissions rising; inventory draw accelerating",
  },
  {
    facilityId: "fac-pune-sdh-1",
    drugId: "drug-artesunate",
    currentStock: 68,
    avgDailyConsumption: 18,
    safetyStock: 180,
    daysCover: 3.8,
    daysCoverPipeline: 6.0,
    pipelineUnits: 40,
    nextDeliveryDays: 9,
    replenishmentStatus: "Delayed",
    riskProbability: 0.88,
    riskStatus: "critical",
    riskDriver: "Irrigation canal belt malaria cluster + delayed batch dispatch",
  },
  {
    facilityId: "fac-pune-sdh-2",
    drugId: "drug-artesunate",
    currentStock: 350,
    avgDailyConsumption: 14,
    safetyStock: 140,
    daysCover: 25.0,
    daysCoverPipeline: 35.7,
    pipelineUnits: 150,
    nextDeliveryDays: 6,
    replenishmentStatus: "On Track",
    riskProbability: 0.10,
    riskStatus: "low",
    riskDriver: "Well-buffered anti-parasitic stock with routine seasonal buffer",
  },
  {
    facilityId: "fac-pune-chc-1",
    drugId: "drug-artesunate",
    currentStock: 100,
    avgDailyConsumption: 10,
    safetyStock: 100,
    daysCover: 10.0,
    daysCoverPipeline: 15.0,
    pipelineUnits: 50,
    nextDeliveryDays: 5,
    replenishmentStatus: "On Track",
    riskProbability: 0.46,
    riskStatus: "warning",
    riskDriver: "Moderate vector cases; order in transit from district depot",
  },
  {
    facilityId: "fac-pune-chc-2",
    drugId: "drug-artesunate",
    currentStock: 240,
    avgDailyConsumption: 8,
    safetyStock: 80,
    daysCover: 30.0,
    daysCoverPipeline: 40.0,
    pipelineUnits: 80,
    nextDeliveryDays: 7,
    replenishmentStatus: "On Track",
    riskProbability: 0.08,
    riskStatus: "low",
    riskDriver: "Low endemic malaria prevalence in highland sector; healthy reserve",
  },
  {
    facilityId: "fac-pune-chc-3",
    drugId: "drug-artesunate",
    currentStock: 70,
    avgDailyConsumption: 6,
    safetyStock: 60,
    daysCover: 11.7,
    daysCoverPipeline: 16.7,
    pipelineUnits: 30,
    nextDeliveryDays: 6,
    replenishmentStatus: "On Track",
    riskProbability: 0.42,
    riskStatus: "warning",
    riskDriver: "Wetland agricultural catchment draw; buffer within warning band",
  },
  {
    facilityId: "fac-pune-phc-1",
    drugId: "drug-artesunate",
    currentStock: 50,
    avgDailyConsumption: 2,
    safetyStock: 20,
    daysCover: 25.0,
    daysCoverPipeline: 35.0,
    pipelineUnits: 20,
    nextDeliveryDays: 7,
    replenishmentStatus: "On Track",
    riskProbability: 0.11,
    riskStatus: "low",
    riskDriver: "Minimal vector caseload, rural inventory securely stocked",
  },
  {
    facilityId: "fac-pune-phc-2",
    drugId: "drug-artesunate",
    currentStock: 9,
    avgDailyConsumption: 3,
    safetyStock: 30,
    daysCover: 3.0,
    daysCoverPipeline: 8.0,
    pipelineUnits: 15,
    nextDeliveryDays: 8,
    replenishmentStatus: "Critical Delay",
    riskProbability: 0.91,
    riskStatus: "critical",
    riskDriver: "Construction worker febrile illness spike; stock nearly exhausted",
  },
  {
    facilityId: "fac-pune-phc-3",
    drugId: "drug-artesunate",
    currentStock: 50,
    avgDailyConsumption: 2,
    safetyStock: 20,
    daysCover: 25.0,
    daysCoverPipeline: 35.0,
    pipelineUnits: 20,
    nextDeliveryDays: 6,
    replenishmentStatus: "On Track",
    riskProbability: 0.12,
    riskStatus: "low",
    riskDriver: "Stable primary dispensary kit with sufficient seasonal reserve",
  },
  {
    facilityId: "fac-thane-dh",
    drugId: "drug-artesunate",
    currentStock: 420,
    avgDailyConsumption: 38,
    safetyStock: 380,
    daysCover: 11.1,
    daysCoverPipeline: 15.8,
    pipelineUnits: 180,
    nextDeliveryDays: 6,
    replenishmentStatus: "Delayed",
    riskProbability: 0.48,
    riskStatus: "warning",
    riskDriver: "Industrial belt vector case influx; buffer dipping towards 10d",
  },
  {
    facilityId: "fac-thane-sdh-1",
    drugId: "drug-artesunate",
    currentStock: 450,
    avgDailyConsumption: 18,
    safetyStock: 180,
    daysCover: 25.0,
    daysCoverPipeline: 33.9,
    pipelineUnits: 160,
    nextDeliveryDays: 5,
    replenishmentStatus: "On Track",
    riskProbability: 0.10,
    riskStatus: "low",
    riskDriver: "Surplus antimalarial stock supplied by state epidemic reserve",
  },
  {
    facilityId: "fac-thane-chc-1",
    drugId: "drug-artesunate",
    currentStock: 45,
    avgDailyConsumption: 12,
    safetyStock: 120,
    daysCover: 3.8,
    daysCoverPipeline: 6.3,
    pipelineUnits: 30,
    nextDeliveryDays: 8,
    replenishmentStatus: "Delayed",
    riskProbability: 0.87,
    riskStatus: "critical",
    riskDriver: "Urban drainage flooding cluster + supplier allocation freeze",
  },
  {
    facilityId: "fac-thane-phc-1",
    drugId: "drug-artesunate",
    currentStock: 26,
    avgDailyConsumption: 2.5,
    safetyStock: 25,
    daysCover: 10.4,
    daysCoverPipeline: 16.4,
    pipelineUnits: 15,
    nextDeliveryDays: 5,
    replenishmentStatus: "On Track",
    riskProbability: 0.46,
    riskStatus: "warning",
    riskDriver: "Tribal block seasonal prophylaxis demand rising",
  },

  // =========================================================================
  // 4. INSULIN REGULAR 40 IU/ML (ENDOCRINE CRITICAL)
  // =========================================================================
  {
    facilityId: "fac-pune-dh",
    drugId: "drug-insulin",
    currentStock: 1600,
    avgDailyConsumption: 50,
    safetyStock: 500,
    daysCover: 32.0,
    daysCoverPipeline: 44.0,
    pipelineUnits: 600,
    nextDeliveryDays: 5,
    replenishmentStatus: "On Track",
    riskProbability: 0.07,
    riskStatus: "low",
    riskDriver: "Deep tertiary endocrinology reserve with dedicated cold chain backup",
  },
  {
    facilityId: "fac-pune-sdh-1",
    drugId: "drug-insulin",
    currentStock: 600,
    avgDailyConsumption: 22,
    safetyStock: 220,
    daysCover: 27.3,
    daysCoverPipeline: 38.6,
    pipelineUnits: 250,
    nextDeliveryDays: 6,
    replenishmentStatus: "On Track",
    riskProbability: 0.09,
    riskStatus: "low",
    riskDriver: "Healthy regional diabetic clinic stock under monthly quota",
  },
  {
    facilityId: "fac-pune-sdh-2",
    drugId: "drug-insulin",
    currentStock: 65,
    avgDailyConsumption: 16,
    safetyStock: 160,
    daysCover: 4.1,
    daysCoverPipeline: 7.2,
    pipelineUnits: 50,
    nextDeliveryDays: 9,
    replenishmentStatus: "Critical Delay",
    riskProbability: 0.90,
    riskStatus: "critical",
    riskDriver: "Sub-station power surge damaged cold storage batch; emergency replenishment pending",
  },
  {
    facilityId: "fac-pune-chc-1",
    drugId: "drug-insulin",
    currentStock: 300,
    avgDailyConsumption: 12,
    safetyStock: 120,
    daysCover: 25.0,
    daysCoverPipeline: 35.0,
    pipelineUnits: 120,
    nextDeliveryDays: 5,
    replenishmentStatus: "On Track",
    riskProbability: 0.11,
    riskStatus: "low",
    riskDriver: "Steady chronic care outpatient distribution with secure buffer",
  },
  {
    facilityId: "fac-pune-chc-2",
    drugId: "drug-insulin",
    currentStock: 35,
    avgDailyConsumption: 10,
    safetyStock: 100,
    daysCover: 3.5,
    daysCoverPipeline: 5.5,
    pipelineUnits: 20,
    nextDeliveryDays: 8,
    replenishmentStatus: "Delayed",
    riskProbability: 0.88,
    riskStatus: "critical",
    riskDriver: "Refrigerated transit van breakdown en route from Pune central store",
  },
  {
    facilityId: "fac-pune-chc-3",
    drugId: "drug-insulin",
    currentStock: 230,
    avgDailyConsumption: 8,
    safetyStock: 80,
    daysCover: 28.8,
    daysCoverPipeline: 41.3,
    pipelineUnits: 100,
    nextDeliveryDays: 6,
    replenishmentStatus: "On Track",
    riskProbability: 0.10,
    riskStatus: "low",
    riskDriver: "Well-managed rural NCD (Non-Communicable Disease) program inventory",
  },
  {
    facilityId: "fac-pune-phc-1",
    drugId: "drug-insulin",
    currentStock: 30,
    avgDailyConsumption: 3,
    safetyStock: 30,
    daysCover: 10.0,
    daysCoverPipeline: 15.0,
    pipelineUnits: 15,
    nextDeliveryDays: 5,
    replenishmentStatus: "On Track",
    riskProbability: 0.45,
    riskStatus: "warning",
    riskDriver: "Limited local cold storage capacity; relies on bi-weekly top-ups",
  },
  {
    facilityId: "fac-pune-phc-2",
    drugId: "drug-insulin",
    currentStock: 32,
    avgDailyConsumption: 4,
    safetyStock: 40,
    daysCover: 8.0,
    daysCoverPipeline: 13.0,
    pipelineUnits: 20,
    nextDeliveryDays: 5,
    replenishmentStatus: "Delayed",
    riskProbability: 0.52,
    riskStatus: "warning",
    riskDriver: "Suburban elderly population surge; stock approaching threshold",
  },
  {
    facilityId: "fac-pune-phc-3",
    drugId: "drug-insulin",
    currentStock: 10,
    avgDailyConsumption: 3,
    safetyStock: 30,
    daysCover: 3.3,
    daysCoverPipeline: 7.3,
    pipelineUnits: 12,
    nextDeliveryDays: 7,
    replenishmentStatus: "Delayed",
    riskProbability: 0.86,
    riskStatus: "critical",
    riskDriver: "Urgent replenishment needed; stock down to 3 days of vials",
  },
  {
    facilityId: "fac-thane-dh",
    drugId: "drug-insulin",
    currentStock: 450,
    avgDailyConsumption: 40,
    safetyStock: 400,
    daysCover: 11.3,
    daysCoverPipeline: 16.3,
    pipelineUnits: 200,
    nextDeliveryDays: 5,
    replenishmentStatus: "On Track",
    riskProbability: 0.44,
    riskStatus: "warning",
    riskDriver: "High outpatient diabetic clinic volume; buffer within watch list",
  },
  {
    facilityId: "fac-thane-sdh-1",
    drugId: "drug-insulin",
    currentStock: 520,
    avgDailyConsumption: 20,
    safetyStock: 200,
    daysCover: 26.0,
    daysCoverPipeline: 36.0,
    pipelineUnits: 200,
    nextDeliveryDays: 6,
    replenishmentStatus: "On Track",
    riskProbability: 0.09,
    riskStatus: "low",
    riskDriver: "Stable endocrine pharmacy supplies under routine procurement",
  },
  {
    facilityId: "fac-thane-chc-1",
    drugId: "drug-insulin",
    currentStock: 120,
    avgDailyConsumption: 12,
    safetyStock: 120,
    daysCover: 10.0,
    daysCoverPipeline: 14.2,
    pipelineUnits: 50,
    nextDeliveryDays: 6,
    replenishmentStatus: "On Track",
    riskProbability: 0.47,
    riskStatus: "warning",
    riskDriver: "Moderate diabetic caseload with routine cold chain buffer",
  },
  {
    facilityId: "fac-thane-phc-1",
    drugId: "drug-insulin",
    currentStock: 10,
    avgDailyConsumption: 2.5,
    safetyStock: 25,
    daysCover: 4.0,
    daysCoverPipeline: 10.0,
    pipelineUnits: 15,
    nextDeliveryDays: 8,
    replenishmentStatus: "Critical Delay",
    riskProbability: 0.89,
    riskStatus: "critical",
    riskDriver: "Cold chain power failure + remote transit disruption",
  },
];
